version: '3'

services:
  keycloak:
      build: 
        context: .
        dockerfile: Dockerfile.18
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
        - 9990:9990