apiVersion: ENC[AES256_GCM,data:/XY=,iv:yAdmCmxNE6lX7yot838d49x07cp5wqzt3bpr/+ZjwmA=,tag:OQVx1qklOCO6CVsU3o/oeA==,type:str]
kind: ENC[AES256_GCM,data:lKlMzlV5,iv:SKzmMeA98CFGlFAlkQh0nU8JYr8yN9rbUnfk2JjLwP8=,tag:i4IOsNKPJ5zh0zQ9VCgXYQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4zda1OOgb+7qtBCtAsdVqw==,iv:SwYj0yI1nGtz0+YyEfcgKu8p5VAWlKg8gc4RLHa1ces=,tag:ACbcXSvIn5roL+NQcAsjPA==,type:str]
    labels:
        branch: ENC[AES256_GCM,data:Nc/s3w==,iv:1aUL1Lt57YWPYTMnO8awwWePjGxkxn1nPDF0g9A5r4Q=,tag:4U9syN2XnujLoRkmKV3nXw==,type:str]
type: ENC[AES256_GCM,data:XMZmNArj,iv:qFrifX3ut8bGrzQMiCm3FJ8EfSg6BF5+Fspul0fQhyI=,tag:sLUgrErkdWxMRb0sILXa6w==,type:str]
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:Wh3NlWw=,iv:kTeJhhhHp7HgxvIKrDcaE0fW9Osq9dtBT5FvDMFcv1s=,tag:OUfRfZhd+HqmiQerul4wQQ==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:Qe0/hZJDgIg=,iv:nFId0H1vknW5CIDWRN/hLeqG/EG8zUYY6sGMj13tay8=,tag:AF/dKmGYxmoDekQD6CaXxw==,type:str]
    PROXY_ADDRESS_FORWARDING: ENC[AES256_GCM,data:PPrqYA==,iv:PXcZ4oGVHbhNV+mz9/nA1kEQGXOqcAPNGLE9CkfwgYE=,tag:+WSWVNKPXWcPi/IQfLD4+A==,type:str]
    KEYCLOAK_HTTP_PORT: ENC[AES256_GCM,data:QCk=,iv:vKYDYHiHzckmVujOFTCDrik1IGYhu0gasRJdVvbfPmA=,tag:x7zhfCtwaqVuF37vT+bHqQ==,type:str]
    KEYCLOAK_HTTPS_PORT: ENC[AES256_GCM,data:p9EM,iv:hNNuv/DdnWo1jjJFLpzU04hvNHfNP8U+wDlZVN8a4uk=,tag:DnWQzjVdspn9mNgZSFiHkA==,type:str]
    KEYCLOAK_HOSTNAME: ENC[AES256_GCM,data:2tJmtczWLZc8s1HJfl+QmoPFUWHDI3dy/h506EStX2ik9zw80mj7VEat5Q==,iv:MCZRu10XrZVpQjunVSwke2V8CBmIhP8foxvyPKuto9o=,tag:v6qTF1+Eo1kqWFrc0RbYLw==,type:str]
    DB_URL: ENC[AES256_GCM,data:ctxL7vVN0YcZy5vZvyHvmN6mz26tRRMjjsC2eByA4h2uP47hrA/xt8xdsKWFeUSHEsykFo7JeHSzmf5JqsKTtpQMMN0axKeEwySYydjMyg==,iv:pOa79WWBmK6dfuOL87dDwoMVL+Da34pB1EIaXHBj9y4=,tag:30bzdpM4i+t+XBhcbSPS7g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:DdArmuFE/griMw2My/Y=,iv:Z3mtuXrgT9F26zT6GaOc7CWlVPFH2iihbxpMY4KlxvU=,tag:B8m1gHFwEPJ9dZvC53x9pg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:fk34vvhcbH08TftnAjEsVIYcdjhTfsiDwfXyD/P5a5ycXxOkTwYJI6beAkJj8bFegAy+WQYi25R+/fkB91LgIQ==,iv:CQXeUjVELxwp8c7x+aKzWa27Bfr7LyQ19xFyLlXGzWo=,tag:9WfUHQWslKHESK1aibmaDA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:443862765029:key/b1739688-ec15-407d-895d-d05ca1217a2f
          created_at: "2023-04-06T11:45:25Z"
          enc: AQICAHjChsodiuiXwUJt0aacmc0yR0oJ/pdUQ2LNOm0pPYSlowGHHn8+NoibU3HX78Hk5oXqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb4x1t6IfcihbvHwBAgEQgDuf3JPm6okOpih4fsaVUO2oDHFJsonGPfWwMCUsXuX/XDozllkwOKDJVSVuveGULfKrYWSLVJ5Fy+ZL0A==
          aws_profile: lambda-doc-rotary
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-06T11:45:26Z"
    mac: ENC[AES256_GCM,data:mqNuO4OJd6810BNchS7n+Lk5xDKxvxgc5C98d/bYUIyJbdGD60s8PFkzpMEn5IwKRzVqo0zjbyA9zgjzLbJXEndmUN02Dazm5nriTex3aWaYz65bLPyQz6x4Pf1Ra0Oah3SVTarycTlF2USHWLMA14Oz9wzocSS7Zn9goMW9/aQ=,iv:5khpG5/IZUUggp6Zir1RqD3peI/0hknBKAjDsSNPzKA=,tag:a1TZ8hpTizfPofzCoM0oPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
